import type { AlbumPhoto, Booking, Expense, Favorite, ItineraryItem, PackingItem, Settlement, ShoppingItem, TodoItem, Trip } from '../types'
import { database, firebaseEnabled } from './firebase'
import { get, ref, set, update } from 'firebase/database'

const key = 'tripmate-data-v1'
type Data = { trips: Trip[]; itinerary: ItineraryItem[]; expenses: Expense[]; settlements: Settlement[]; todos: TodoItem[]; packingItems: PackingItem[]; bookings: Booking[]; favorites: Favorite[]; albumPhotos: AlbumPhoto[]; shoppingItems: ShoppingItem[]; categoryBudgets: Record<string, Record<string, number>> }
const seed: Data = { trips: [], itinerary: [], expenses: [], settlements: [], todos: [], packingItems: [], bookings: [], favorites: [], albumPhotos: [], shoppingItems: [], categoryBudgets: {} }
const read = (): Data => ({ ...seed, ...(JSON.parse(localStorage.getItem(key) || JSON.stringify(seed)) as Partial<Data>) })
const write = (data: Data) => localStorage.setItem(key, JSON.stringify(data))
const id = () => crypto.randomUUID()
const withoutUndefined = (data: Record<string, unknown>) => Object.fromEntries(Object.entries(data).filter(([, value]) => value !== undefined))

export const repository = {
  async getData(userId?: string) {
    const db = database; if (!firebaseEnabled || !db || !userId) return read()
    const tripIndex = (await get(ref(db, `userTrips/${userId}`))).val() as Record<string, boolean> | null
    const ids = Object.keys(tripIndex || {})
    const tripRows = await Promise.all(ids.map(async (tripId) => {
      const [tripSnapshot, membersSnapshot, itinerarySnapshot, expensesSnapshot, settlementsSnapshot, todosSnapshot, packingSnapshot, bookingsSnapshot, favoritesSnapshot, albumSnapshot, shoppingSnapshot, personalBudgetSnapshot, categoryBudgetsSnapshot] = await Promise.all([
        get(ref(db, `trips/${tripId}`)), get(ref(db, `tripMembers/${tripId}`)),
        get(ref(db, `itineraryItems/${tripId}`)), get(ref(db, `expenses/${tripId}`)), get(ref(db, `settlements/${tripId}`)), get(ref(db, `todos/${tripId}`)), get(ref(db, `packingItems/${tripId}`)), get(ref(db, `bookings/${tripId}`)), get(ref(db, `favorites/${tripId}`)), get(ref(db, `albums/${tripId}`)), get(ref(db, `shoppingItems/${tripId}`)), get(ref(db, `tripMemberBudgets/${tripId}/${userId}`)), get(ref(db, `budgets/${tripId}/categories`)),
      ])
      const trip = tripSnapshot.val() as Omit<Trip, 'members'> | null
      if (!trip) return null
      const personalBudget = Number(personalBudgetSnapshot.val()) || 0
      return { trip: { ...trip, id: tripId, members: Object.entries(membersSnapshot.val() || {}).map(([id, value]) => ({ id, ...(value as Omit<Trip['members'][number], 'id'>), personalBudget: id === userId ? personalBudget : 0 })) }, itinerary: Object.entries(itinerarySnapshot.val() || {}).map(([id, value]) => ({ id, ...(value as Omit<ItineraryItem, 'id'>) })), expenses: Object.entries(expensesSnapshot.val() || {}).map(([id, value]) => ({ id, ...(value as Omit<Expense, 'id'>) })), settlements: Object.entries(settlementsSnapshot.val() || {}).map(([id, value]) => ({ id, ...(value as Omit<Settlement, 'id'>) })), todos: Object.entries(todosSnapshot.val() || {}).map(([id, value]) => ({ id, tripId, scope: (value as TodoItem).scope || 'shared', ...(value as Omit<TodoItem, 'id' | 'tripId'>) })), packingItems: Object.entries(packingSnapshot.val() || {}).map(([id, value]) => ({ id, tripId, ...(value as Omit<PackingItem, 'id' | 'tripId'>) })), bookings: Object.entries(bookingsSnapshot.val() || {}).map(([id, value]) => ({ id, tripId, ...(value as Omit<Booking, 'id' | 'tripId'>) })), favorites: Object.entries(favoritesSnapshot.val() || {}).map(([id, value]) => ({ id, tripId, ...(value as Omit<Favorite, 'id' | 'tripId'>), addedToItinerary: Boolean((value as Favorite).addedToItinerary) })), albumPhotos: Object.entries(albumSnapshot.val() || {}).map(([id, value]) => ({ id, tripId, ...(value as Omit<AlbumPhoto, 'id' | 'tripId'>) })), shoppingItems: Object.entries(shoppingSnapshot.val() || {}).map(([id, value]) => ({ id, tripId, ...(value as Omit<ShoppingItem, 'id' | 'tripId'>) })), categoryBudgets: { [tripId]: Object.fromEntries(Object.entries(categoryBudgetsSnapshot.val() || {}).map(([category, amount]) => [category, Math.max(0, Number(amount) || 0)])) } }
    }))
    return tripRows.filter((row): row is NonNullable<typeof row> => Boolean(row)).reduce<Data>((data, row) => ({ trips: [...data.trips, row.trip], itinerary: [...data.itinerary, ...row.itinerary], expenses: [...data.expenses, ...row.expenses], settlements: [...data.settlements, ...row.settlements], todos: [...data.todos, ...row.todos], packingItems: [...data.packingItems, ...row.packingItems], bookings: [...data.bookings, ...row.bookings], favorites: [...data.favorites, ...row.favorites], albumPhotos: [...data.albumPhotos, ...row.albumPhotos], shoppingItems: [...data.shoppingItems, ...row.shoppingItems], categoryBudgets: { ...data.categoryBudgets, ...row.categoryBudgets } }), seed)
  },
  async addTrip(input: Omit<Trip, 'id' | 'inviteCode'>, userId?: string) {
    const trip = { ...input, id: id(), inviteCode: Math.random().toString(36).slice(2, 8).toUpperCase() }
    const db = database; if (firebaseEnabled && db && userId) { const { members, ...tripData } = trip; const updates: Record<string, unknown> = { [`trips/${trip.id}`]: tripData, [`tripInvites/${trip.inviteCode}`]: { tripId: trip.id, createdBy: userId, role: 'editor', enabled: true, usedCount: 0, maxUses: 20, createdAt: Date.now() }, [`userTrips/${userId}/${trip.id}`]: true }; members.forEach((member) => { updates[`tripMembers/${trip.id}/${member.id}`] = { name: member.name, email: member.email, role: member.role }; updates[`userTrips/${member.id}/${trip.id}`] = true }); await update(ref(db), updates); return trip }
    const d = read(); d.trips.push(trip); write(d); return trip
  },
  async updateTrip(trip: Trip) { const db = database; if (firebaseEnabled && db) { const { members, id: tripId, ...data } = trip; await set(ref(db, `trips/${tripId}`), data); await set(ref(db, `tripMembers/${tripId}`), Object.fromEntries(members.map(({ id, personalBudget: _personalBudget, ...member }) => [id, member]))); return } const d = read(); d.trips = d.trips.map((x) => x.id === trip.id ? trip : x); write(d) },
  async deleteTrip(trip: Trip) { const db = database; if (firebaseEnabled && db) { const updates: Record<string, null> = { [`trips/${trip.id}`]: null, [`tripMembers/${trip.id}`]: null, [`tripMemberBudgets/${trip.id}`]: null, [`budgets/${trip.id}`]: null, [`itineraryItems/${trip.id}`]: null, [`expenses/${trip.id}`]: null, [`settlements/${trip.id}`]: null, [`todos/${trip.id}`]: null, [`packingItems/${trip.id}`]: null, [`bookings/${trip.id}`]: null, [`favorites/${trip.id}`]: null, [`albums/${trip.id}`]: null, [`shoppingItems/${trip.id}`]: null, [`tripInvites/${trip.inviteCode}`]: null }; trip.members.forEach((member) => { updates[`userTrips/${member.id}/${trip.id}`] = null }); await update(ref(db), updates); return } const d = read(); d.trips = d.trips.filter((x) => x.id !== trip.id); d.itinerary = d.itinerary.filter((x) => x.tripId !== trip.id); d.expenses = d.expenses.filter((x) => x.tripId !== trip.id); d.settlements = d.settlements.filter((x) => x.tripId !== trip.id); d.todos = d.todos.filter((x) => x.tripId !== trip.id); d.packingItems = d.packingItems.filter((x) => x.tripId !== trip.id); d.bookings = d.bookings.filter((x) => x.tripId !== trip.id); d.favorites = d.favorites.filter((x) => x.tripId !== trip.id); d.albumPhotos = d.albumPhotos.filter((x) => x.tripId !== trip.id); d.shoppingItems = d.shoppingItems.filter((x) => x.tripId !== trip.id); delete d.categoryBudgets[trip.id]; write(d) },
  async addMember(trip: Trip, member: Omit<Trip['members'][number], 'id'>) {
    const db = database; if (firebaseEnabled && db) { const emailKey = member.email.toLowerCase().replace(/[.#$\[\]/]/g, '_'); const memberId = (await get(ref(db, `emailIndex/${emailKey}`))).val() as string | null; if (!memberId) throw new Error('這位旅伴尚未登入 TripMate，請請對方先完成登入後再邀請。'); await update(ref(db), { [`tripMembers/${trip.id}/${memberId}`]: member, [`userTrips/${memberId}/${trip.id}`]: true }); return { id: memberId, ...member } }
    const result = { id: id(), ...member }; trip.members.push(result); await this.updateTrip(trip); return result
  },
  async removeMember(trip: Trip, memberId: string) {
    const db = database
    if (firebaseEnabled && db) { await update(ref(db), { [`tripMembers/${trip.id}/${memberId}`]: null, [`userTrips/${memberId}/${trip.id}`]: null, [`tripMemberBudgets/${trip.id}/${memberId}`]: null }); return }
    const d = read(); const storedTrip = d.trips.find((entry) => entry.id === trip.id); if (storedTrip) storedTrip.members = storedTrip.members.filter((member) => member.id !== memberId); write(d)
  },
  async updatePersonalBudget(trip: Trip, memberId: string, personalBudget: number) {
    const budget = Math.max(0, Number(personalBudget) || 0); const db = database
    if (firebaseEnabled && db) { await set(ref(db, `tripMemberBudgets/${trip.id}/${memberId}`), budget); return }
    const d = read(); const storedTrip = d.trips.find((entry) => entry.id === trip.id); const storedMember = storedTrip?.members.find((entry) => entry.id === memberId); if (storedMember) storedMember.personalBudget = budget; write(d)
  },
  async updateCategoryBudgets(trip: Trip, categoryBudgets: Record<string, number>) {
    const budgets = Object.fromEntries(Object.entries(categoryBudgets).map(([category, amount]) => [category, Math.max(0, Number(amount) || 0)]).filter(([, amount]) => Number(amount) > 0))
    const db = database; if (firebaseEnabled && db) { await set(ref(db, `budgets/${trip.id}/categories`), budgets); return }
    const d = read(); d.categoryBudgets[trip.id] = budgets; write(d)
  },
  async addTodo(input: Omit<TodoItem, 'id' | 'completed' | 'createdAt'>) { const todo = { ...input, id: id(), completed: false, createdAt: Date.now() }; const db = database; if (firebaseEnabled && db) { const { id: todoId, tripId, ...data } = todo; await set(ref(db, `todos/${tripId}/${todoId}`), data); return todo } const d = read(); d.todos.push(todo); write(d); return todo },
  async updateTodo(todo: TodoItem) { const db = database; if (firebaseEnabled && db) { const { id: todoId, tripId, ...data } = todo; await set(ref(db, `todos/${tripId}/${todoId}`), data); return } const d = read(); d.todos = d.todos.map((entry) => entry.id === todo.id ? todo : entry); write(d) },
  async toggleTodo(todo: TodoItem) { const db = database; if (firebaseEnabled && db) { await update(ref(db, `todos/${todo.tripId}/${todo.id}`), { completed: !todo.completed }); return } const d = read(); const target = d.todos.find((entry) => entry.id === todo.id); if (target) target.completed = !target.completed; write(d) },
  async deleteTodo(todo: TodoItem) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `todos/${todo.tripId}/${todo.id}`), null); return } const d = read(); d.todos = d.todos.filter((entry) => entry.id !== todo.id); write(d) },
  async addPackingItem(input: Omit<PackingItem, 'id' | 'completed' | 'createdAt'>) { const item = { ...input, id: id(), completed: false, createdAt: Date.now() }; const db = database; if (firebaseEnabled && db) { const { id: itemId, tripId, ...data } = item; await set(ref(db, `packingItems/${tripId}/${itemId}`), data); return item } const d = read(); d.packingItems.push(item); write(d); return item },
  async updatePackingItem(item: PackingItem) { const db = database; if (firebaseEnabled && db) { const { id: itemId, tripId, ...data } = item; await set(ref(db, `packingItems/${tripId}/${itemId}`), data); return } const d = read(); d.packingItems = d.packingItems.map((entry) => entry.id === item.id ? item : entry); write(d) },
  async reorderPackingItems(items: PackingItem[]) { if (!items.length) return; const db = database; if (firebaseEnabled && db) { const updates: Record<string, number> = {}; items.forEach((item, order) => { updates[`packingItems/${item.tripId}/${item.id}/order`] = order }); await update(ref(db), updates); return } const orders = new Map(items.map((item, order) => [item.id, order])); const d = read(); d.packingItems = d.packingItems.map((item) => orders.has(item.id) ? { ...item, order: orders.get(item.id) } : item); write(d) },
  async togglePackingItem(item: PackingItem) { const db = database; if (firebaseEnabled && db) { await update(ref(db, `packingItems/${item.tripId}/${item.id}`), { completed: !item.completed }); return } const d = read(); const target = d.packingItems.find((entry) => entry.id === item.id); if (target) target.completed = !target.completed; write(d) },
  async deletePackingItem(item: PackingItem) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `packingItems/${item.tripId}/${item.id}`), null); return } const d = read(); d.packingItems = d.packingItems.filter((entry) => entry.id !== item.id); write(d) },
  async addBooking(input: Omit<Booking, 'id' | 'createdAt'>) { const booking = { ...input, id: id(), createdAt: Date.now() }; const db = database; if (firebaseEnabled && db) { const { id: bookingId, tripId, ...data } = booking; await set(ref(db, `bookings/${tripId}/${bookingId}`), data); return booking } const d = read(); d.bookings.push(booking); write(d); return booking },
  async updateBooking(booking: Booking) { const db = database; if (firebaseEnabled && db) { const { id: bookingId, tripId, ...data } = booking; await set(ref(db, `bookings/${tripId}/${bookingId}`), data); return } const d = read(); d.bookings = d.bookings.map((entry) => entry.id === booking.id ? booking : entry); write(d) },
  async deleteBooking(booking: Booking) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `bookings/${booking.tripId}/${booking.id}`), null); return } const d = read(); d.bookings = d.bookings.filter((entry) => entry.id !== booking.id); write(d) },
  async addFavorite(input: Omit<Favorite, 'id' | 'createdAt' | 'addedToItinerary'>) { const favorite = { ...input, id: id(), addedToItinerary: false, createdAt: Date.now() }; const db = database; if (firebaseEnabled && db) { const { id: favoriteId, tripId, ...data } = favorite; await set(ref(db, `favorites/${tripId}/${favoriteId}`), data); return favorite } const d = read(); d.favorites.push(favorite); write(d); return favorite },
  async updateFavorite(favorite: Favorite) { const db = database; if (firebaseEnabled && db) { const { id: favoriteId, tripId, ...data } = favorite; await set(ref(db, `favorites/${tripId}/${favoriteId}`), data); return } const d = read(); d.favorites = d.favorites.map((entry) => entry.id === favorite.id ? favorite : entry); write(d) },
  async deleteFavorite(favorite: Favorite) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `favorites/${favorite.tripId}/${favorite.id}`), null); return } const d = read(); d.favorites = d.favorites.filter((entry) => entry.id !== favorite.id); write(d) },
  async addAlbumPhoto(input: Omit<AlbumPhoto, 'id' | 'createdAt'>) { const photo = { ...input, id: id(), createdAt: Date.now() }; const db = database; if (firebaseEnabled && db) { const { id: photoId, tripId, ...data } = photo; await set(ref(db, `albums/${tripId}/${photoId}`), data); return photo } const d = read(); d.albumPhotos.push(photo); write(d); return photo },
  async updateAlbumPhoto(photo: AlbumPhoto) { const db = database; if (firebaseEnabled && db) { const { id: photoId, tripId, ...data } = photo; await set(ref(db, `albums/${tripId}/${photoId}`), data); return } const d = read(); d.albumPhotos = d.albumPhotos.map((entry) => entry.id === photo.id ? photo : entry); write(d) },
  async deleteAlbumPhoto(photo: AlbumPhoto) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `albums/${photo.tripId}/${photo.id}`), null); return } const d = read(); d.albumPhotos = d.albumPhotos.filter((entry) => entry.id !== photo.id); write(d) },
  async addShoppingItem(input: Omit<ShoppingItem, 'id' | 'createdAt' | 'updatedAt'>) { const item = { ...input, id: id(), createdAt: Date.now(), updatedAt: Date.now() }; const db = database; if (firebaseEnabled && db) { const { id: itemId, tripId, ...data } = item; await set(ref(db, `shoppingItems/${tripId}/${itemId}`), withoutUndefined(data)); return item } const d = read(); d.shoppingItems.push(item); write(d); return item },
  async updateShoppingItem(item: ShoppingItem) { const updated = { ...item, updatedAt: Date.now() }; const db = database; if (firebaseEnabled && db) { const { id: itemId, tripId, ...data } = updated; await set(ref(db, `shoppingItems/${tripId}/${itemId}`), withoutUndefined(data)); return updated } const d = read(); d.shoppingItems = d.shoppingItems.map((entry) => entry.id === item.id ? updated : entry); write(d); return updated },
  async deleteShoppingItem(item: ShoppingItem) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `shoppingItems/${item.tripId}/${item.id}`), null); return } const d = read(); d.shoppingItems = d.shoppingItems.filter((entry) => entry.id !== item.id); write(d) },
  async addItinerary(input: Omit<ItineraryItem, 'id' | 'completed'>) { const item = { ...input, id: id(), completed: false }; const db = database; if (firebaseEnabled && db) { const { id: itemId, ...data } = item; await set(ref(db, `itineraryItems/${item.tripId}/${itemId}`), data); return item } const d = read(); d.itinerary.push(item); write(d); return item },
  async updateItinerary(item: ItineraryItem) { const db = database; if (firebaseEnabled && db) { const { id: itemId, tripId, ...data } = item; await set(ref(db, `itineraryItems/${tripId}/${itemId}`), data); return } const d = read(); d.itinerary = d.itinerary.map((entry) => entry.id === item.id ? item : entry); write(d) },
  async reorderItinerary(items: ItineraryItem[]) { if (!items.length) return; const db = database; if (firebaseEnabled && db) { const updates: Record<string, number> = {}; items.forEach((item, order) => { updates[`itineraryItems/${item.tripId}/${item.id}/order`] = order }); await update(ref(db), updates); return } const orders = new Map(items.map((item, order) => [item.id, order])); const d = read(); d.itinerary = d.itinerary.map((item) => orders.has(item.id) ? { ...item, order: orders.get(item.id) } : item); write(d) },
  async deleteItinerary(item: ItineraryItem) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `itineraryItems/${item.tripId}/${item.id}`), null); return } const d = read(); d.itinerary = d.itinerary.filter((entry) => entry.id !== item.id); write(d) },
  async toggleItinerary(itemId: string, item?: ItineraryItem) { const db = database; if (firebaseEnabled && db && item) { await update(ref(db, `itineraryItems/${item.tripId}/${itemId}`), { completed: !item.completed }); return } const d = read(); const target = d.itinerary.find((x) => x.id === itemId); if (target) target.completed = !target.completed; write(d) },
  async addExpense(input: Omit<Expense, 'id'>) { const expense = { ...input, id: id() }; const db = database; if (firebaseEnabled && db) { const { id: expenseId, ...data } = expense; await set(ref(db, `expenses/${expense.tripId}/${expenseId}`), data); return expense } const d = read(); d.expenses.push(expense); write(d); return expense },
  async updateExpense(expense: Expense) { const db = database; if (firebaseEnabled && db) { const { id: expenseId, tripId, ...data } = expense; await set(ref(db, `expenses/${tripId}/${expenseId}`), data); return } const d = read(); d.expenses = d.expenses.map((item) => item.id === expense.id ? expense : item); write(d) },
  async deleteExpense(expense: Expense) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `expenses/${expense.tripId}/${expense.id}`), null); return } const d = read(); d.expenses = d.expenses.filter((item) => item.id !== expense.id); write(d) },
  async addSettlement(input: Omit<Settlement, 'id'>) { const settlement = { ...input, id: id() }; const db = database; if (firebaseEnabled && db) { const { id: settlementId, ...data } = settlement; await set(ref(db, `settlements/${settlement.tripId}/${settlementId}`), data); return settlement } const d = read(); d.settlements.push(settlement); write(d); return settlement },
  async deleteSettlement(settlement: Settlement) { const db = database; if (firebaseEnabled && db) { await set(ref(db, `settlements/${settlement.tripId}/${settlement.id}`), null); return } const d = read(); d.settlements = d.settlements.filter((item) => item.id !== settlement.id); write(d) },
}
