interface Env { ALLOWED_ORIGIN: string; FIREBASE_DATABASE_URL: string; FIREBASE_WEB_API_KEY: string; CLOUDINARY_CLOUD_NAME: string; CLOUDINARY_API_KEY: string; CLOUDINARY_API_SECRET: string; FIREBASE_SERVICE_ACCOUNT_JSON: string }
interface User { localId: string; email?: string; displayName?: string }
interface Invite { tripId: string; createdBy: string; role?: 'editor' | 'viewer'; enabled?: boolean; expiresAt?: number; maxUses?: number; usedCount?: number }
const enc = new TextEncoder()
const b64 = (v: Uint8Array | string) => btoa(typeof v === 'string' ? v : String.fromCharCode(...v)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '')
const pem = (v: string) => Uint8Array.from(atob(v.replace(/-----(BEGIN|END) [A-Z ]+-----/g, '').replace(/\s/g, '')), x => x.charCodeAt(0)).buffer
const out = (body: unknown, status: number, origin?: string | null) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json', ...(origin ? { 'Access-Control-Allow-Origin': origin, Vary: 'Origin' } : {}) } })
async function user(request: Request, env: Env): Promise<User> { const token = request.headers.get('Authorization')?.match(/^Bearer (.+)$/)?.[1]; if (!token) throw new Error('Missing authentication token.'); const r = await fetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=' + env.FIREBASE_WEB_API_KEY, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ idToken: token }) }); const d = await r.json() as { users?: User[] }; if (!r.ok || !d.users?.[0]) throw new Error('Invalid authentication token.'); return d.users[0] }
async function token(env: Env): Promise<string> { const a = JSON.parse(env.FIREBASE_SERVICE_ACCOUNT_JSON) as { client_email: string; private_key: string; token_uri?: string }; const now = Math.floor(Date.now() / 1000); const h = b64(JSON.stringify({ alg: 'RS256', typ: 'JWT' })); const p = b64(JSON.stringify({ iss: a.client_email, scope: 'https://www.googleapis.com/auth/firebase.database https://www.googleapis.com/auth/userinfo.email', aud: a.token_uri || 'https://oauth2.googleapis.com/token', iat: now, exp: now + 3600 })); const key = await crypto.subtle.importKey('pkcs8', pem(a.private_key), { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' }, false, ['sign']); const sig = b64(new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5', key, enc.encode(h + '.' + p)))); const r = await fetch(a.token_uri || 'https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer', assertion: h + '.' + p + '.' + sig }) }); const d = await r.json() as { access_token?: string }; if (!r.ok || !d.access_token) throw new Error('Firebase service authentication failed.'); return d.access_token }
async function db<T>(env: Env, path: string, method: 'GET' | 'PATCH', body?: unknown): Promise<T> { const r = await fetch(env.FIREBASE_DATABASE_URL.replace(/\/$/, '') + '/' + path + '.json', { method, headers: { Authorization: 'Bearer ' + await token(env), ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); if (!r.ok) throw new Error('Firebase database request failed.'); return r.json() as Promise<T> }
async function sha1(v: string): Promise<string> { const d = await crypto.subtle.digest('SHA-1', enc.encode(v)); return [...new Uint8Array(d)].map(x => x.toString(16).padStart(2, '0')).join('') }
export default { async fetch(request: Request, env: Env): Promise<Response> { const origin = request.headers.get('Origin'); const allowed = Boolean(origin && env.ALLOWED_ORIGIN.split(',').map(value => value.trim()).includes(origin)); if (request.method === 'OPTIONS') return new Response(null, { status: allowed ? 204 : 403, headers: allowed && origin ? { 'Access-Control-Allow-Origin': origin, 'Access-Control-Allow-Headers': 'Authorization, Content-Type', 'Access-Control-Allow-Methods': 'POST, OPTIONS', Vary: 'Origin' } : {} }); if (!allowed) return out({ error: 'Origin is not allowed.' }, 403); if (request.method !== 'POST') return out({ error: 'Method not allowed.' }, 405, origin); try { const me = await user(request, env); const path = new URL(request.url).pathname; if (path === '/v1/cloudinary/signature') { const body = await request.json() as { kind?: string }; const kind = body.kind === 'album' || body.kind === 'shopping' ? body.kind : 'cover'; const timestamp = Math.floor(Date.now() / 1000); const folder = `tripmate/${kind === 'album' ? 'albums' : kind === 'shopping' ? 'shopping' : 'covers'}/${me.localId}`; return out({ timestamp, signature: await sha1('folder=' + folder + '&timestamp=' + timestamp + env.CLOUDINARY_API_SECRET), apiKey: env.CLOUDINARY_API_KEY, cloudName: env.CLOUDINARY_CLOUD_NAME, folder }, 200, origin) } if (path === '/v1/trips/join') { const body = await request.json() as { code?: string }; const code = body.code?.trim().toUpperCase(); if (!code) return out({ error: 'Invite code is required.' }, 400, origin); const invite = await db<Invite | null>(env, 'tripInvites/' + code, 'GET'); if (!invite || invite.enabled === false || (invite.expiresAt && invite.expiresAt < Date.now()) || (invite.maxUses && (invite.usedCount || 0) >= invite.maxUses)) return out({ error: 'Invite code is invalid or expired.' }, 404, origin); const trip = await db<{ ownerId?: string } | null>(env, 'trips/' + invite.tripId, 'GET'); if (!trip || trip.ownerId !== invite.createdBy) return out({ error: 'Invite verification failed.' }, 403, origin); await db(env, '', 'PATCH', { ['tripMembers/' + invite.tripId + '/' + me.localId]: { name: me.displayName || me.email?.split('@')[0] || 'Companion', email: me.email || '', role: invite.role || 'editor', joinedAt: Date.now() }, ['userTrips/' + me.localId + '/' + invite.tripId]: true, ['tripInvites/' + code + '/usedCount']: (invite.usedCount || 0) + 1 }); return out({ tripId: invite.tripId }, 200, origin) } return out({ error: 'Route not found.' }, 404, origin) } catch (e) { return out({ error: e instanceof Error ? e.message : 'Worker error.' }, 401, origin) } } } satisfies ExportedHandler<Env>
