<script setup lang="ts">
import { reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import TripBookingCard from '../components/TripBookingCard.vue'
import type { Booking, Trip } from '../types'
import { useTripStore } from '../stores/trip'

const props = defineProps<{ trip: Trip; bookings: Booking[]; canEdit: boolean; userId: string; memberName: (id: string) => string }>()
const store = useTripStore()
const open = ref(false)
const editingId = ref<string | null>(null)
const form = reactive({ type: 'flight' as Booking['type'], title: '', startDate: '', endDate: '', location: '', bookingNumber: '', bookedBy: '', contact: '', website: '', note: '' })
function openForm(existing?: Booking) { if (!props.canEdit) return ElMessage.warning('Viewer 僅能查看旅行預訂，無法修改。'); editingId.value = existing?.id || null; Object.assign(form, existing ? { type: existing.type, title: existing.title, startDate: existing.startDate, endDate: existing.endDate || '', location: existing.location || '', bookingNumber: existing.bookingNumber || '', bookedBy: existing.bookedBy || '', contact: existing.contact || '', website: existing.website || '', note: existing.note || '' } : { type: 'flight', title: '', startDate: '', endDate: '', location: '', bookingNumber: '', bookedBy: '', contact: '', website: '', note: '' }); open.value = true }
async function save() { if (!form.title.trim() || !form.startDate) return ElMessage.warning('請填寫預訂名稱與開始日期。'); try { const raw = form.website.trim(); const payload = { tripId: props.trip.id, type: form.type, title: form.title.trim(), startDate: form.startDate, endDate: form.endDate || '', location: form.location.trim(), bookingNumber: form.bookingNumber.trim(), bookedBy: form.bookedBy || '', contact: form.contact.trim(), website: raw && !/^https?:\/\//i.test(raw) ? `https://${raw}` : raw, note: form.note.trim(), createdBy: props.userId || props.trip.ownerId }; const existing = editingId.value ? props.bookings.find((entry) => entry.id === editingId.value) : undefined; if (existing) await store.updateBooking({ ...existing, ...payload }); else await store.addBooking(payload); open.value = false; ElMessage.success('旅行預訂已儲存。') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '無法儲存旅行預訂。') } }
async function remove(booking: Booking) { if (!props.canEdit) return ElMessage.warning('Viewer 僅能查看旅行預訂，無法修改。'); try { await ElMessageBox.confirm(`確定刪除預訂「${booking.title}」嗎？`, '刪除旅行預訂', { confirmButtonText: '刪除', cancelButtonText: '取消', type: 'warning' }); await store.deleteBooking(booking); ElMessage.success('旅行預訂已刪除。') } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error(error instanceof Error ? error.message : '無法刪除旅行預訂。') } }
</script>

<template><section class="trip-bookings-view" aria-label="旅行預訂"><TripBookingCard :trip="trip" :bookings="bookings" :can-edit-trip="canEdit" :member-name="memberName" @add="openForm()" @edit="openForm" @remove="remove" /><el-dialog v-model="open" :title="editingId ? '編輯旅行預訂' : '新增旅行預訂'" width="min(92vw, 560px)"><el-form label-position="top"><div class="two-col"><el-form-item label="預訂類型"><el-select v-model="form.type"><el-option label="機票" value="flight" /><el-option label="住宿" value="hotel" /><el-option label="交通" value="transport" /><el-option label="票券" value="ticket" /><el-option label="餐廳" value="restaurant" /><el-option label="其他" value="other" /></el-select></el-form-item><el-form-item label="預訂名稱"><el-input v-model="form.title" /></el-form-item></div><div class="two-col"><el-form-item label="開始日期"><el-date-picker v-model="form.startDate" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="結束日期（選填）"><el-date-picker v-model="form.endDate" type="date" value-format="YYYY-MM-DD" /></el-form-item></div><el-form-item label="地點（選填）"><el-input v-model="form.location" /></el-form-item><div class="two-col"><el-form-item label="預訂編號（選填）"><el-input v-model="form.bookingNumber" /></el-form-item><el-form-item label="預訂人（選填）"><el-select v-model="form.bookedBy" clearable><el-option v-for="m in trip.members" :key="m.id" :label="m.name" :value="m.id" /></el-select></el-form-item></div><div class="two-col"><el-form-item label="聯絡方式（選填）"><el-input v-model="form.contact" /></el-form-item><el-form-item label="預訂網站（選填）"><el-input v-model="form.website" /></el-form-item></div><el-form-item label="備註（選填）"><el-input v-model="form.note" type="textarea" :rows="2" /></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" @click="save">儲存預訂</el-button></template></el-dialog></section></template>
<style scoped>.trip-bookings-view{display:grid;grid-column:1/-1;min-width:0}</style>
