<script setup lang="ts">
import TripItineraryCard from '../components/TripItineraryCard.vue'
import type { ItineraryItem, ShoppingItem } from '../types'
type Day = { date: string; entries: ItineraryItem[] }
defineProps<{ days: Day[]; personalItems: ItineraryItem[]; shoppingItems: ShoppingItem[]; canEdit: boolean; sortingEnabled: boolean; formatDate: (date: string) => string; duration: (entry: ItineraryItem) => string; timeWarning: (entries: ItineraryItem[], index: number) => string; mapsUrl: (location: string, mapUrl?: string) => string }>()
const emit = defineEmits<{ add: []; addAfter: [entry: ItineraryItem]; addPersonal: [group: ItineraryItem]; toggle: [entry: ItineraryItem]; edit: [entry: ItineraryItem]; remove: [entry: ItineraryItem]; toggleSorting: []; sort: [payload: { date: string; oldIndex: number; newIndex: number }]; sortPersonal: [payload: { parentId: string; oldIndex: number; newIndex: number }]; sortGroup: [payload: { groupId: string; oldIndex: number; newIndex: number }]; move: [payload: { itemId: string; from: string; to: string; oldIndex: number; newIndex: number }]; createGroup: [payload: { entries: ItineraryItem[] }]; editGroup: [group: ItineraryItem]; dissolveGroup: [group: ItineraryItem] }>()
</script>
<template><section class="trip-itinerary-view" aria-label="每日行程"><TripItineraryCard :days="days" :personal-items="personalItems" :shopping-items="shoppingItems" :can-edit-trip="canEdit" :sorting-enabled="sortingEnabled" :format-date="formatDate" :duration="duration" :time-warning="timeWarning" :maps-url="mapsUrl" @add="emit('add')" @add-after="emit('addAfter',$event)" @add-personal="emit('addPersonal',$event)" @toggle="emit('toggle',$event)" @edit="emit('edit',$event)" @remove="emit('remove',$event)" @create-group="emit('createGroup',$event)" @edit-group="emit('editGroup',$event)" @dissolve-group="emit('dissolveGroup',$event)" @toggle-sorting="emit('toggleSorting')" @sort="emit('sort',$event)" @sort-group="emit('sortGroup',$event)" @sort-personal="emit('sortPersonal',$event)" @move="emit('move',$event)" /></section></template>
<style scoped>.trip-itinerary-view{display:grid;min-width:0}</style>
