import { defineStore } from 'pinia'
import type { Booking, Expense, Favorite, ItineraryItem, Member, PackingItem, Settlement, TodoItem, Trip } from '../types'
import { repository } from '../services/repository'

export const useTripStore = defineStore('trips', {
  state: () => ({ trips: [] as Trip[], itinerary: [] as ItineraryItem[], expenses: [] as Expense[], settlements: [] as Settlement[], todos: [] as TodoItem[], packingItems: [] as PackingItem[], bookings: [] as Booking[], favorites: [] as Favorite[], categoryBudgets: {} as Record<string, Record<string, number>>, loading: false }),
  getters: { trip: (s) => (id: string) => s.trips.find((x) => x.id === id), items: (s) => (id: string) => s.itinerary.filter((x) => x.tripId === id), tripExpenses: (s) => (id: string) => s.expenses.filter((x) => x.tripId === id), tripSettlements: (s) => (id: string) => s.settlements.filter((x) => x.tripId === id), tripTodos: (s) => (id: string) => s.todos.filter((x) => x.tripId === id), tripPackingItems: (s) => (id: string) => s.packingItems.filter((x) => x.tripId === id), tripBookings: (s) => (id: string) => s.bookings.filter((x) => x.tripId === id), tripFavorites: (s) => (id: string) => s.favorites.filter((x) => x.tripId === id), tripCategoryBudgets: (s) => (id: string) => s.categoryBudgets[id] || {} },
  actions: {
    async load(userId?: string) { this.loading = true; try { Object.assign(this, await repository.getData(userId)) } finally { this.loading = false } },
    async createTrip(input: Omit<Trip, 'id' | 'inviteCode'>, userId?: string) { const trip = await repository.addTrip(input, userId); this.trips.push(trip); return trip },
    async updateTrip(trip: Trip) { await repository.updateTrip(trip); const index = this.trips.findIndex((item) => item.id === trip.id); if (index >= 0) this.trips.splice(index, 1, trip) },
    async deleteTrip(trip: Trip) { await repository.deleteTrip(trip); this.trips = this.trips.filter((item) => item.id !== trip.id); this.itinerary = this.itinerary.filter((item) => item.tripId !== trip.id); this.expenses = this.expenses.filter((item) => item.tripId !== trip.id); this.settlements = this.settlements.filter((item) => item.tripId !== trip.id); this.todos = this.todos.filter((item) => item.tripId !== trip.id); this.packingItems = this.packingItems.filter((item) => item.tripId !== trip.id); this.bookings = this.bookings.filter((item) => item.tripId !== trip.id); this.favorites = this.favorites.filter((item) => item.tripId !== trip.id); delete this.categoryBudgets[trip.id] },
    async addMember(trip: Trip, member: Omit<Member, 'id'>) { const added = await repository.addMember(trip, member); trip.members.push(added) },
    async removeMember(trip: Trip, memberId: string) { await repository.removeMember(trip, memberId); const index = trip.members.findIndex((member) => member.id === memberId); if (index >= 0) trip.members.splice(index, 1) },
    async updatePersonalBudget(tripId: string, memberId: string, personalBudget: number) { const trip = this.trip(tripId); if (!trip) return; await repository.updatePersonalBudget(trip, memberId, personalBudget); const member = trip.members.find((entry) => entry.id === memberId); if (member) member.personalBudget = Math.max(0, Number(personalBudget) || 0) },
    async updateCategoryBudgets(tripId: string, categoryBudgets: Record<string, number>) { const trip = this.trip(tripId); if (!trip) return; await repository.updateCategoryBudgets(trip, categoryBudgets); this.categoryBudgets[tripId] = Object.fromEntries(Object.entries(categoryBudgets).map(([category, amount]) => [category, Math.max(0, Number(amount) || 0)]).filter(([, amount]) => Number(amount) > 0)) },
    async addTodo(input: Omit<TodoItem, 'id' | 'completed' | 'createdAt'>) { const todo = await repository.addTodo(input); this.todos.push(todo) },
    async updateTodo(todo: TodoItem) { await repository.updateTodo(todo); const index = this.todos.findIndex((item) => item.id === todo.id); if (index >= 0) this.todos.splice(index, 1, todo) },
    async toggleTodo(todo: TodoItem) { await repository.toggleTodo(todo); todo.completed = !todo.completed },
    async deleteTodo(todo: TodoItem) { await repository.deleteTodo(todo); this.todos = this.todos.filter((item) => item.id !== todo.id) },
    async addPackingItem(input: Omit<PackingItem, 'id' | 'completed' | 'createdAt'>) { const item = await repository.addPackingItem(input); this.packingItems.push(item) },
    async updatePackingItem(item: PackingItem) { await repository.updatePackingItem(item); const index = this.packingItems.findIndex((entry) => entry.id === item.id); if (index >= 0) this.packingItems.splice(index, 1, item) },
    async reorderPackingItems(items: PackingItem[]) { const previousOrders = new Map(this.packingItems.map((item) => [item.id, item.order])); items.forEach((item, order) => { item.order = order }); try { await repository.reorderPackingItems(items) } catch (error) { this.packingItems.forEach((item) => { item.order = previousOrders.get(item.id) }); throw error } },
    async togglePackingItem(item: PackingItem) { await repository.togglePackingItem(item); item.completed = !item.completed },
    async deletePackingItem(item: PackingItem) { await repository.deletePackingItem(item); this.packingItems = this.packingItems.filter((entry) => entry.id !== item.id) },
    async addBooking(input: Omit<Booking, 'id' | 'createdAt'>) { const booking = await repository.addBooking(input); this.bookings.push(booking) },
    async updateBooking(booking: Booking) { await repository.updateBooking(booking); const index = this.bookings.findIndex((entry) => entry.id === booking.id); if (index >= 0) this.bookings.splice(index, 1, booking) },
    async deleteBooking(booking: Booking) { await repository.deleteBooking(booking); this.bookings = this.bookings.filter((entry) => entry.id !== booking.id) },
    async addFavorite(input: Omit<Favorite, 'id' | 'createdAt' | 'addedToItinerary'>) { const favorite = await repository.addFavorite(input); this.favorites.push(favorite) },
    async updateFavorite(favorite: Favorite) { await repository.updateFavorite(favorite); const index = this.favorites.findIndex((entry) => entry.id === favorite.id); if (index >= 0) this.favorites.splice(index, 1, favorite) },
    async deleteFavorite(favorite: Favorite) { await repository.deleteFavorite(favorite); this.favorites = this.favorites.filter((entry) => entry.id !== favorite.id) },
    async addItem(input: Omit<ItineraryItem, 'id' | 'completed'>) { const item = await repository.addItinerary(input); this.itinerary.push(item); return item },
    async updateItem(item: ItineraryItem) { await repository.updateItinerary(item); const index = this.itinerary.findIndex((entry) => entry.id === item.id); if (index >= 0) this.itinerary.splice(index, 1, item) },
    async reorderItems(items: ItineraryItem[]) { const previousOrders = new Map(this.itinerary.map((item) => [item.id, item.order])); items.forEach((item, order) => { item.order = order }); try { await repository.reorderItinerary(items) } catch (error) { this.itinerary.forEach((item) => { item.order = previousOrders.get(item.id) }); throw error } },
    async deleteItem(item: ItineraryItem) { await repository.deleteItinerary(item); this.itinerary = this.itinerary.filter((entry) => entry.id !== item.id) },
    async toggleItem(id: string) { const item = this.itinerary.find((x) => x.id === id); await repository.toggleItinerary(id, item); if (item) item.completed = !item.completed },
    async addExpense(input: Omit<Expense, 'id'>) { const expense = await repository.addExpense(input); this.expenses.push(expense) },
    async updateExpense(expense: Expense) { await repository.updateExpense(expense); const index = this.expenses.findIndex((item) => item.id === expense.id); if (index >= 0) this.expenses.splice(index, 1, expense) },
    async deleteExpense(expense: Expense) { await repository.deleteExpense(expense); this.expenses = this.expenses.filter((item) => item.id !== expense.id) },
    async addSettlement(input: Omit<Settlement, 'id'>) { const settlement = await repository.addSettlement(input); this.settlements.push(settlement) },
    async deleteSettlement(settlement: Settlement) { await repository.deleteSettlement(settlement); this.settlements = this.settlements.filter((item) => item.id !== settlement.id) },
  },
})
